### ISSUE TITLE
X64dbg stopped working(04.04.2017)

### ISSUE THREAD

**Issue by lugery** [x64dbg/x64dbg#1522]
Hello,
I'm facing this problem..I hope it is resolved

X64dbg_version: 4 April 2017
Win 7 Home Basic/x64

  Problematic Event Name:	APPCRASH
  Uygulama Adı:	x32dbg.exe
  Uygulama Sürümü:	0.0.2.5
  Uygulama Zaman Damgası:	58e3c30e
  Hata Modülü Adı:	dbghelp.dll
  Hata Modülü Sürümü:	6.3.9600.16384
  Hata Modülü Zaman Damgası:	52158c87
  Özel Durum Kodu:	c0000005
  Özel Durum Uzaklığı:	00100ec7
  OS Sürümü:	6.1.7601.2.1.0.768.2
  Yerel Kimlik:	1055
  Ek Bilgiler 1:	2b38
  Ek Bilgiler 2:	2b388bd11c33aa31792212073f24d74e
  Ek Bilgiler 3:	45b6
  Ek Bilgiler 4:	45b6338217eac254090a4c69b7032094

**Comment by blaquee** [comment]
Not enough information. Could you provide us with information on how to reproduce this crash. Whats the target application? what did you do? when did it crash?

**Comment by mrfearless** [comment]
Also a list of programs running in memory might be useful to see if any are injecting their own .dlls - anti-virus or multi-monitor support programs for example.

**Comment by lugery** [comment]
Thanks for the answers.. :)
[Report.txt](https://github.com/x64dbg/x64dbg/files/901486/Report.txt)
It happens when you go to step F8..  It happens suddenly. Sometimes happen.
I do not use antivirus.

**Comment by blaquee** [comment]
Looks like the crash occurs in dgbhelp.dll. Would you be able to generate a usermode crash dump file? Or some stack trace. The report still doesnt provide enough information to work with.

**Comment by lugery** [comment]
Thanks for the answer.. :)
I use a laptop. Has Single Screen. :)
Definitely an error in dgbhelp.dll.
"Print Screen" does not even work when there is an error.
X64dbg stops completely. I can not get user mode crash dump file :(
Windows Crash Dump(Please, convert .txt->.dmp):
[x32dbg.exe.4092.txt](https://github.com/x64dbg/x64dbg/files/906061/x32dbg.exe.4092.txt)

:

**Comment by mrexodia** [comment]
This should have been fixed by #1526

**Comment by jnowe** [comment]
I still have the issue when I close x32dbg

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	598134a7
  Fault Module Name:	StackHash_53c1
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c000041d
  Exception Offset:	00470fef
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1036
  Additional Information 1:	53c1
  Additional Information 2:	53c174a42c4a07592884a1bb525b0e87
  Additional Information 3:	a101
  Additional Information 4:	a101ee5ed6ddc602eda9c33c409a562b

I'm using Windows 7-x64 SP1 with VS 2013, 2015 and 2017 (all CE) installed. I have done nothing special. I start the debugger and then close it and I still get this error. No issue with x64dbg. By the way, I'm a beginner in debugging.

**Comment by jk2K** [comment]
x64dbg crash when mouse hovers over a pointer in the dump

![x32dbg-hover-on-pointer-crash](https://user-images.githubusercontent.com/4025839/42725108-f37d919e-87b0-11e8-86fa-777d284ff1f0.gif)

- the program being debugged can be any program, x64dbg always crash
- win10 1803
- resolution: 3840 x 2160
- x64dbg version: 2018.07.05

**Comment by mrexodia** [comment]
@jk2K Can you send the *.dmp files in the `minidump` directory (from the date where you saw the crash)?

**Comment by jk2K** [comment]
here, thanks for helping

[dump-14072018_2312100842.zip](https://github.com/x64dbg/x64dbg/files/2195044/dump-14072018_2312100842.zip)

**Comment by mrexodia** [comment]
Thanks for the dump. I found the issue and I think I will fix it tomorrow. In the meantime you can use a little older version.

@torusrxxx This crash happened before. It’s because “mLine” is outside of the disassembly buffer in the CPUSideBar. I think this can happen if the bottom of the views is not aligned perfectly.

**Comment by mrexodia** [comment]
Okay @jk2K your issue should be fixed now. It might take a few minutes before the build is complete. I think this issue is also fixed now so I will close it too.
