### ISSUE TITLE
Test program with PDB symbols available causes x32dbg to hang

### ISSUE THREAD

**Issue by ViRb3** [x64dbg/x64dbg#1571]
I created a simple C++ console app in VS 2017. I built the Debug version and tried to open it in x32dbg. The debugger hangs in this state: ![](https://i.imgur.com/HWymphk.png)
and none of the buttons do anything. 
Closing it causes an infinite hang until I force stop the process. If I move the PDB symbols in another directory or rename them so that x32dbg doesn't find them, this problem is gone. 
Same issue with a snapshot of 1-2 months ago.

Here are both files: https://d.filebox.moe/vexonpc.zip 
Original directory: `C:\Users\Admin\Documents\Visual Studio 2017\Projects\TestApp\Debug`

**Comment by ViRb3** [comment]
@mrexodia Did you put the files in the correct path so x64dbg tries to auto-load the symbols?
`C:\Users\Admin\Documents\Visual Studio 2017\Projects\TestApp\Debug\TestApp.exe`
`C:\Users\Admin\Documents\Visual Studio 2017\Projects\TestApp\Debug\TestApp.pdb`

**Comment by mrexodia** [comment]
I didn't, that's what the "not reproduced" label means 👍

**Comment by mrexodia** [comment]
Okay it should be fixed now.

**Comment by ljani** [comment]
I can still reproduce this issue with `snapshot_2017-06-08_22-37.zip`.

**Comment by Mattiwatti** [comment]
I can't reproduce this issue, but I did notice the PDB in the zip is a 'partial' PDB (from the dumb /DEBUG:FASTLINK switch that was made the default in VS2017). dbghelp.dll 10.0.15063.0 sees this and tells you it can't use the PDB file. dbghelp 8.1 (which comes with x64dbg releases) doesn't recognise this type of crippled PDB.

**Comment by ljani** [comment]
For what it's worth, I'm on Windows 10.0.15063.483 x64 and `x32dbg.exe` from `snapshot_2017-07-09_20-21.zip` and still having the issue. The file opens fine in the debugger, but when you navigate to the `Symbols` tab and try to click some of the modules, x64dbg hangs...

But just now I was able to open the tab once, select different modules etc. So it seems it's some kind of race condition which triggers most of time for me?

I've made a 180MB `x32dbg.exe` dump. If you're related to the project, please let me know and I'll share a link with you in private.

**Comment by alexgdi** [comment]
still not fix

**Comment by mrexodia** [comment]
The bug is in dbghelp, there is no fix but updating.

**Comment by Mattiwatti** [comment]
![howtodoit](https://i.imgur.com/gpIwaCU.png)
This is the only correct value of this field.

**Comment by sn00w** [comment]
it's a VS IDE bug. reported them lots of times. if you turn off linkers's suppress startup banner - u well see that there wrong /DEBUG key passed to link.exe. it causes WinDbg to fail with symbols too btw.
so just clear the line Generate Debug Info, goto Command Line, and write additional /DEBUG key

**Comment by mrexodia** [comment]
Should be fixed by the symbol refactor.
