### ISSUE TITLE
Symbols undecoration doesn't work

### ISSUE THREAD

**Issue by TheOggY** [x64dbg/x64dbg#2183]
I've stumbled upon an issue in one of the latest versions of debugger: symbols undecoration doens't seem to work.
This is what I see in version May 19, 2019:
![изображение](https://user-images.githubusercontent.com/51228579/58692365-24ab0980-8397-11e9-9bd5-3478381d8a0a.png)
And this is the same symbol, but in version May 17, 2018:
![изображение](https://user-images.githubusercontent.com/51228579/58692552-7f446580-8397-11e9-8a66-2b2ba3fcc41e.png)

The option 'Undecorate Symbol Names' doesn't affect the issue at all.

**Comment by mrexodia** [comment]
Should be fixed now, please check.

**Comment by TheOggY** [comment]
Hi! Thank you for response and sorry for late reaction.
I've checked the latest version (snapshot_2019-11-26_13-35), but the issue still persists. For example, here is how auto-label for the symbol of std::exception ctor looks like:
![изображение](https://user-images.githubusercontent.com/51228579/69655516-bdd98500-1087-11ea-8ce4-e5bc8f0450b2.png)
The option 'Undecorate Symbol Names' doesn't change anything.
This reproduces for every binary I've tried, also on different installations.
