### ISSUE TITLE
X32Dbg Crash Bug

### ISSUE THREAD

**Issue by a627414850** [x64dbg/x64dbg#2945]
Operating System
win ver:  Win7 X64  6.1.7601

x64dbg Version
snapshot_2022-09-10_01-57.zip

Crash Info:
  应用程序名: x32dbg.exe
  应用程序版本: 0.0.2.5
  应用程序时间戳: 631bd25c
  故障模块名称: x32dbg.dll
  故障模块版本: 0.0.0.0
  故障模块时间戳: 631bd274
  异常代码: c0000005
  异常偏移: 00076010

Crash location in x32dbg.dll :
![image](https://user-images.githubusercontent.com/13477188/193462797-f1de00aa-daa4-4ddd-8fda-550bc8a4e7a4.png)

I Find in  Source:
https://github.com/x64dbg/x64dbg/blob/bc88c853777245df59385d77d374d1c9110842a3/src/dbg/memory.cpp#L141
https://github.com/x64dbg/x64dbg/blob/bc88c853777245df59385d77d374d1c9110842a3/src/dbg/memory.cpp#L143

typedef struct _IMAGE_OPTIONAL_HEADER
{
........
+38h DWORD SectionAlignment; // 内存中的区块的对齐大小
+50h DWORD SizeOfImage; // 映像装入内存后的总尺寸

Maybe Add  _try  _except to Catch The Exception ?

**Comment by mrexodia** [comment]
Can you share the minidump (should be in x32\minidump)? It looks the same as an old issue which I fixed. Try to use the latest version…

**Comment by a627414850** [comment]
> Can you share the minidump (should be in x32\minidump)? It looks the same as an old issue which I fixed. Try to use the latest version…

Thank you for reply。

I use the latest version of snapshot_ 2022-09-25_ 14-55, it still crash：

问题事件名称: APPCRASH
  应用程序名: x32dbg.exe
  应用程序版本: 0.0.2.5
  应用程序时间戳: 63304f4b
  故障模块名称: x32dbg.dll
  故障模块版本: 0.0.0.0
  故障模块时间戳: 63304f63
  异常代码: c0000005
  异常偏移: 00076448
  OS 版本: 6.1.7601.2.1.0.256.1
  区域设置 ID: 2052
  其他信息 1: 0a9e
  其他信息 2: 0a9e372d3b4ad19135b953a78882e789
  其他信息 3: 0a9e
  其他信息 4: 0a9e372d3b4ad19135b953a78882e789
  
  Minidump file:
[dump-03102022_0054370753.zip](https://github.com/x64dbg/x64dbg/files/9693055/dump-03102022_0054370753.zip)

**Comment by mrfearless** [comment]
`ScyllaHideX64DBGPlugin.dp32	D:\snapshot_2022-09-25_14-55\release\x32\plugins\ScyllaHideX64DBGPlugin.dp32	1.4.750.0`

Could be anti debugging - debugger detected and thus crashes. Or could be that plugin.

**Comment by a627414850** [comment]
> 

But the day before yesterday, the crash did not occur. The crash started after updating the debugged program

**Comment by a627414850** [comment]
> `ScyllaHideX64DBGPlugin.dp32 D:\snapshot_2022-09-25_14-55\release\x32\plugins\ScyllaHideX64DBGPlugin.dp32 1.4.750.0`
> 
> Could be anti debugging - debugger detected and thus crashes. Or could be that plugin.

But the day before yesterday, the crash did not occur. The crash started after updating the debugged program

**Comment by mrexodia** [comment]
Thanks for the crash dump! Can you share what you were debugging? It looks like for some reason the `modInfo->headers` is a `nullptr`. This shouldn't happen under normal circumstances...

**Comment by a627414850** [comment]
> Thanks for the crash dump! Can you share what you were debugging? It looks like for some reason the `modInfo->headers` is a `nullptr`. This shouldn't happen under normal circumstances...

Yes, I think so。
But I don't have a compilation environment，Unable to debug

**Comment by mrexodia** [comment]
I meant if you could share the program you were debugging (what's causing the crash)...

**Comment by a627414850** [comment]
> I meant if you could share the program you were debugging (what's causing the crash)...

Can you give me the x32dbg PDB file? I try to debug without source code

**Comment by a627414850** [comment]
> I meant if you could share the program you were debugging (what's causing the crash)...

program is a game 。https://yl.qq.com/down.shtml

**Comment by mrexodia** [comment]
The PDB is always posted on GitHub: https://github.com/x64dbg/x64dbg/releases/download/snapshot-pdb/snapshot_2022-09-25_14-55-pdb.zip let me know a place to upload if it's not suitable for you...

The main information I need is the DLL that is causing this problem. Do you also get a message in the log like "Module %s%s: invalid PE file!"?

**Comment by mrexodia** [comment]
I will try to install the game... Does it happen right away or do you need to do something special?

**Comment by a627414850** [comment]
> I will try to install the game... Does it happen right away or do you need to do something special?

You need to install the ScyllaHide plug-in to x32dbg and terminate the wegame related processes except the main game program

**Comment by a627414850** [comment]
> I will try to install the game... Does it happen right away or do you need to do something special?
ScyllaHide plugin config :
![image](https://user-images.githubusercontent.com/13477188/193470259-267be1a4-5a5c-429c-89f7-fe6488ef7bce.png)

**Comment by mrexodia** [comment]
Unfortunately I cannot log in to the game (don't have WeChat). I pushed a workaround, but let me know which DLL is causing it (should be logged now) and I will continue investigating.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2022-09-25_14-55.zip

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbg/commit/420ef52aeaf4d3d3940acf69f8aa69d0cc76728c

**Comment by a627414850** [comment]
> Unfortunately I cannot log in to the game (don't have WeChat). I pushed a workaround, but let me know which DLL is causing it (should be logged now) and I will continue investigating.

Thanks for fixing the bug(https://github.com/x64dbg/x64dbg/blob/6c3d3941cbe358f8fe3c9da9463b0c65fa2cf081/src/dbg/memory.cpp#L146).

Now I find that the game anti-cheat driver gave a fake PE header structure to x32dbg, because x32dbg will not crash when the anti-cheat driver does not work. I guess it should be specially used for anti-attach. Recently, I was very busy, so I did not continue to study. I'll give you a fake PE header structure when I'm not busy later

**Comment by mrexodia** [comment]
Could you share the driver .sys file? Then I can take a look at how it works.

**Comment by a627414850** [comment]
> Could you share the driver .sys file? Then I can take a look at how it works.

Sorry, I'm a geological prospector. I don't have a computer with me, but only a mobile phone. I'll give you what you need when I finish my work. Anti cheating driver is a part of the game, and can't work alone without the game.
