### ISSUE TITLE
Stepping out of a breakpoint corrupts a stack value after encountering two PUSHF instructions (TitanEngine)

### ISSUE THREAD

**Issue by shocoman** [x64dbg/x64dbg#3122]
**Gif** (look how I push one values to the stack but get slightly different ones):

![pushfd_test_2](https://github.com/x64dbg/x64dbg/assets/8329446/a650e733-b7b1-46d9-8e68-01b389573131)

The last one is especially neat, it's just a singleshoot software breakpoint and one pushfd. The users can easily get the bug if this instruction is the very first one at the entry point. This is how I got it. The first hundred or so times I thought it was just some anti-debugging measure that I somehow circumvented by attaching to the program at a later stage, but alas, although I guess it very much could be. The bug has been present since the oldest version I found (circa 2014). Additionally, GleeBug has a similar issue in all these cases: if there are two or more PUSHFDs in a row, it will correctly refrain from pushing the trap flag after the first instruction, but will include it in all the rest. I don't know, maybe that's intentional, and the programmers/users are supposed to clear it themselves with callbacks.

**Fix (maybe)**:
I don't know much about debuggers and how they are built. But by looking into the source code I noticed that the variable[ "PushfBPX"](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L46) (which is meant to [clear the trap flag ](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L645)after a breakpoint) is only toggled when breakpoints should be reset at the next single-step exception. This is true for all cases except for the [software breakpoint handler](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L517). There, the actual trap flag is only toggled if the breakpoint is[n't singleshoot](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L544C35-L544C35), but "PushfBPX" [is assigned "true](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L562C30-L562C30)" every time when the current instruction is PUSHF and Co. So, as a fix, I suggest adding the check "FoundBreakPoint.BreakPointType != UE_SINGLESHOOT" as an if statement around [@@@@@](https://github.com/x64dbg/TitanEngine/blob/882bc1bc30cb7cdd409b00dbf722b7bb09a62576/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp#L561C1-L561C1) This seems to be sufficient.

**Comment by mrexodia** [comment]
Yeah this is a bug for sure, thanks for the report! If you have some time a pull request would be appreciated, otherwise I'll get to it in a week or two probably.

**Comment by Security0Try** [comment]
I invite you to join our Telegram chat dedicated to information security and discuss the solution there: t.me/offsec0chat

**Comment by mrexodia** [comment]
Should be fixed in GleeBug now as well, thanks for the detailed report!

**Comment by shocoman** [comment]
Hello @mrexodia 
I noticed that this bug is still present in [the latest build](https://github.com/x64dbg/x64dbg/releases/tag/snapshot) (both with TitanEngine and GleeBug, x32 and x64). According to the DLLs metadata, they were last modified at "‎7/‎8/‎2023 ‏‎2:47 PM" which seems correct. Is there something that needs to be done?

**Comment by mrexodia** [comment]
In my local testing everything was fine. I'll retest if I have some time...
