### ISSUE TITLE
Bitdefender blocking access to x32dbg.exe

### ISSUE THREAD

**Issue by TheAifam5** [x64dbg/x64dbg#371]
Hi,
of course i added the exclusions for x32 and x64, but after enable "On-access scanning" still I cant run.
with disabled "On-access scanning" works.

Regards TheAifam5

**Comment by Nukem9** [comment]
This isn't within our control. It's a false positive most likely because of the imported functions used (Read/WriteProcessMemory), which are commonly in malware.

Anyone will need to whitelist it manually.

**Comment by mrexodia** [comment]
Might be solved once I sign the release.

**Comment by TheAifam5** [comment]
Also whitelisted lol. Read again

**Comment by mrexodia** [comment]
In my opinion BitDefender is crap. Their whitelisting is broken. I had
serious issues with this, even after I contacted them about it. They said
it was a known problem and fixed in the 2015 edition. I ended up wasting
whatever a license cost me to buy MalwareBytes.

This issue might be solved automatically once we go to signed releases, but
there is not much we can do about it at the moment.

**Comment by TheAifam5** [comment]
@mrexodia its not fixed .. i have Bitdefender 2015 Total Security

**Comment by mrexodia** [comment]
I didn't do anything, so it's not fixed indeed
