### ISSUE TITLE
Assembling with an immediate-address pointer is wrongly parsed (64-bit version only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#416]
This was previously mentioned here: https://github.com/x64dbg/x64dbg/issues/356#issuecomment-130933919

- This issue is related to the 64-bit version of the debugger only.

---------------------------------------------------------------
__*Problem 1:__ (__Solved__)
When you assemble an instruction and one of its operands is an immediate-address pointer
(example: __`mov qword ptr [7FFFFFFFF8E], 3`__, __`lea RAX, qword ptr [7FFFFFFFF8E]`__, ...etc.)
that operand in the assembled instruction will have a different address.

Examples:
![mov_err](https://cloud.githubusercontent.com/assets/11916365/10829137/0265b2ae-7e81-11e5-9732-d8618d5bf803.png)
![lea_err](https://cloud.githubusercontent.com/assets/11916365/10829143/0e831a22-7e81-11e5-8223-71c5a0c29018.png)
![assm_at_err2](https://cloud.githubusercontent.com/assets/11916365/10829166/2ecd621a-7e81-11e5-96d6-9e148606378c.png)

---------------------------------------------------------------
__*Problem 2:__ (__Solved__)
I couldn't put this into words, but i guess the description would be: immediate-address pointers are
EDIT: decreased by __`0x7`__

Those pics clearly explain the issue:

Correct (build 10-20)
![i2_1](https://cloud.githubusercontent.com/assets/11916365/10829764/ad27f7e4-7e84-11e5-93b5-66b544ee3d9a.png)

Wrong (build 10-28)
![i2_2](https://cloud.githubusercontent.com/assets/11916365/10829767/b269807e-7e84-11e5-85b9-9c963a927049.png)

---------------------------------------------------------------
__*Problem 3:__ (__duplicate of__ #434)
I'm not sure if this is actually an issue, so please forgive me if this is something correct.

1) Select an instruction with an immediate-address pointer.
2) Press space.
3) The "Assemble at ..." window will show the immediate address relative to the instruction address

![assm_at_err](https://cloud.githubusercontent.com/assets/11916365/10829649/e1425c28-7e83-11e5-889c-9f4f5b32c637.png)

**Comment by wk-952** [comment]
Also forgot to mention that when i built the whole project with Nukem9's fork ( with this commit: https://github.com/Nukem9/x64dbg/commit/e19196781cadb5fdb6e0f65b655a63625c0377da ), this issue was not present

**Comment by mrexodia** [comment]
Try the main snapshot, there might have been a bug in the disassembly.

**Comment by wk-952** [comment]
Which snapshot do you mean ?
i used the one on jenkins (snapshot_2015-10-28_05-28.7z)

**Comment by mrexodia** [comment]
Right, nevermind then probably the disassembly is wrong in my snapshot. I
dont get the point about building nukems branch though

**Comment by wk-952** [comment]
I manually compiled Nukem's branch at the time this https://github.com/Nukem9/x64dbg/commit/e19196781cadb5fdb6e0f65b655a63625c0377da was the last commit made, and when i tested it against this issue, the debugger was working properly with no signs of wrong instruction-assembling/parsing.
So what i meant is that maybe you could merge his branch, since also he fixed the issue of the scrolling,
so i suppose there are no extra work to be done (considering both issues) if you merged his branch or used his code.

**Comment by mrexodia** [comment]
His branch also has stuff that shouldnt be merged. My guess is that the
capstone messed it up.

**Comment by wk-952** [comment]
Not 100% because as mentioned in the first post, this was an old issue (before switching to capstone) that i mentioned briefly in another issue and Nukem suggested that it's a XEDParse issue,
but it definitely became more messed up after capstone (previously problems 2 and 3 were not present).

**Comment by Nukem9** [comment]
* was typing this, @wk-952 submitted before I did

Problem 1:
- You probably found a bug in XEDParse

Problem 2/3:
- My branch still uses BeaEngine, so Capstone is just being parsed differently when displayed (and can probably be fixed)

**Comment by mrexodia** [comment]
issue 3 was introduced by the capstone branch for sure (encountered it myself).
issue 2 was also introduced by the capstone branch (pretty sure, checking now)
issue 1 is indeed xedparse i'd say.

**Comment by mrexodia** [comment]
@wk-952 could you confirm whether this issue has been fixed or not?

**Comment by wk-952** [comment]
i'm using this commit https://github.com/x64dbg/x64dbg/commit/81377dd4b009262515782d32b3851ef5400b9fb0 (snapshot_2015-10-29_11-55) and issue 2 is partially solved since the analysis engine of the debugger is still analyzing the wrong address (check the pics of problem 2).

As for issue 1 some instructions would be assembled correctly as:
'lea xxx, qword ptr [address]' and 'mov xxx, qword ptr [address]' (both will be assembled as expected)
but other instructions won't, like 'add qword ptr [address], xxx'
![issue_1](https://cloud.githubusercontent.com/assets/11916365/11013521/dceb2460-8519-11e5-8567-59d86eb6f2ab.png)
also the above-mentioned 'mov' instruction would fail if the operands were swapped
i.e the immediate-address pointer is the first arg of the instruction like 'mov qword ptr [address], xxx'
![1st_oprand](https://cloud.githubusercontent.com/assets/11916365/11013522/e535b658-8519-11e5-95c6-965008597ce2.png)

Issue 3 isn't solved, but i guess it's not a big deal or of importance as compared to the other 2.

**Comment by mrexodia** [comment]
good to hear some stuff was fixed!

issue 1 is still weird, but definitely an issue in XEDParse (although in the original description it was a combination of XEDParse and incorrect disassembly).

issue 3 is on my TODO list, shouldn't be hard but I was just a little lazy.

**Comment by wk-952** [comment]
yep, noticed that issue 1 was combination after the above tests,
one last thing i just noticed now,

assembling ``mov **byte** ptr [address], xxx`` will add *1* to the address
assembling ``mov **word** ptr [address], xxx`` will add *2* to the address
assembling ``mov **qword**/**dword** ptr [address], xxx`` will add *4* to the address,
while ``add/sub byte/word/dword/qword ptr [address], xxx`` will increase the address by 1

i'm not sure if this would help in any way, but at least consider them in your tests

**Comment by Nukem9** [comment]
Fixed now with the merge?

**Comment by mrexodia** [comment]
No idea lol

**Comment by wk-952** [comment]
no, this is still not fixed
![err](https://cloud.githubusercontent.com/assets/11916365/11384397/0bddb4e8-9318-11e5-88ba-266d1e6e4190.png)

**Comment by mrexodia** [comment]
I tried to assemble this earlier but I couldnt get it to work :D

**Comment by Nukem9** [comment]
https://github.com/x64dbg/XEDParse/issues/1
