### ISSUE TITLE
The error message "immediate size is too large" is not always triggered (XEDParse + Keystone)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#540]
`Keystone` only:

`cmp dword ptr ds:[eax], 0x123456789` will be truncated to
`cmp dword ptr ds:[eax], 0x23456789`

`mov eax, 0x123456789` will be truncated to
`mov eax, 0x23456789`

-----------------

`XEDParse` only:

`mov rax, 0x12345678901234567` will be truncated to
`mov rax, 0x2345678901234567`

`mov rax, 0x123456789012345678` will be truncated to
`mov rax, 0x3456789012345678`

`mov rax, 0x1234567890123456789` will be truncated to
`mov rax, 0x4567890123456`

------------------

old:
~~`cmp qword ptr [rax], 0x123456789`, will be truncated to
`cmp qword ptr [rax], 0x23456789`~~

**Comment by wk-952** [comment]
Completely off-topic:
Could you please add the new version of XEDParse to the future snapshots ?
You're still providing the old one with the immediate-address pointer issue.

**Comment by mrexodia** [comment]
Oh, I will try to update it today. Thought I had already updated.

**Comment by wk-952** [comment]
Original post updated, some of the cases are solved.

**Comment by wk-952** [comment]
Original post updated again, some of the cases are related to `XEDParse` only, while the others are related to `Keystone` only.

**Comment by mrexodia** [comment]
XEDParse issues with this should be fixed (should be in the snapshot within 1 hour), for bug reports on Keystone, please report them at https://github.com/keystone-engine/keystone/issues

![s](http://i.imgur.com/fO0E2v1.png)

**Comment by wk-952** [comment]
Did you mean that there will be future commits for this ?
Because i've tried version `1.0.26` of `XEDParse` just now and still the same.

**Comment by mrexodia** [comment]
The number parser in x64dbg also needed updating to fix this. The latest build is needed.

**Comment by wk-952** [comment]
I guess it's safe to close here now, since `XEDParse`'s issue is solved.
As for `Keystone` this was already reported, i made a reference to this issue from there.

**Comment by wk-952** [comment]
The `Keystone` issue was solved too if you want to update.
Just a reminder for you.

**Comment by mrexodia** [comment]
Thanks, will update keystone when I'm back home.
