### ISSUE TITLE
Wrong coloring and spacing of instructions in CPU tab (GUI only)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#722]
- To reproduce this issue, set the font of the `Disassembly` to anything bigger than 8 (or less than that).
- Using latest snapshot `snapshot_2016-06-05_09-44.7z`

Notice how the 2 words `ptr` and the segment register are concatenated,
also the immediate memory address is not completely painted (or excessively painted if font < 8).
Increasing or decreasing the font produces different output.
pic 1:
![err](https://cloud.githubusercontent.com/assets/11916365/15808742/f1b8171a-2b7f-11e6-99e3-306e61591f77.jpg)

pic 2:
![err2](https://cloud.githubusercontent.com/assets/11916365/15808753/1d5636fe-2b80-11e6-88e9-03d1f8d2c5c4.jpg)

**Comment by wk-952** [comment]
@mrexodia I wanted to start testing the debugger again today regarding the db issue,
so despite this GUI bug, is it ok to use this snapshot for testing or should i wait ?

**Comment by mrexodia** [comment]
You can try the one of two days ago. I rewrote some of the painting code
but I'm going to sleep now so I can't fix it.

**Comment by torusrxxx** [comment]
I know what's happening. I have fixed it on my local branch.

**Comment by mrexodia** [comment]
should be fixed now

**Comment by blaquee** [comment]
This is not fixed. Just used latest snapshot and having the highlighting issues.
Also the Registers view still suffers from the clipping of the addresses.
<img width="738" alt="clipping" src="https://cloud.githubusercontent.com/assets/1324227/15829558/412190da-2be2-11e6-91ee-8cb498c9ac84.PNG">

**Comment by mrexodia** [comment]
Did you use the sourceforge or the github snapshot? They are always
slightly out of sync.

I didn't touch the registers view as far as I know...

**Comment by blaquee** [comment]
I always use the github snapshot

**Comment by wk-952** [comment]
I tried this issue now on `snapshot_2016-06-06_06-15` and it it's partially solved (although the first post didn't describe the following).

This is a picture in which all fonts are set to `12`: (all is good)
![1](https://cloud.githubusercontent.com/assets/11916365/15863256/890acf42-2cd2-11e6-8fe4-abc80a122962.png)

This is another picture with all fonts set to `6`: (all is good too)
![2](https://cloud.githubusercontent.com/assets/11916365/15863280/a2af504e-2cd2-11e6-9220-094ee782be49.png)

Also changing the resolution of the monitor doesn't cause any issues, but there is still one problem with `HexDump`.
If the font of the `HexDump` and `General Tables` are different, then the `HexDump` will be completely messed up, take a look at this picture:
![3](https://cloud.githubusercontent.com/assets/11916365/15863416/30b585a2-2cd3-11e6-9279-b8a9d66c450a.jpg)

- Using Win10 x64
- No DPI scaling or custom fonts are applied to Windows.

**Comment by torusrxxx** [comment]
The problem with dump window will be resolved in pull request #730.
